# arXiv RAG System Configuration
# Public configuration settings

app:
  name: "arXiv RAG System"
  version: "1.0.0"
  
# arXiv API settings
arxiv:
  max_results: 10
  sort_by: "relevance"
  timeout: 30
  
# Document processing settings
document:
  chunk_size: 512
  chunk_overlap: 50
  max_file_size_mb: 50
  
# RAG engine settings
rag:
  model_name: "gpt-3.5-turbo"
  temperature: 0.0
  max_tokens: 1000
  top_k: 3
  
# ChromaDB settings
chromadb:
  host: "localhost"
  port: 8000
  collection_name: "arxiv_documents"
  persist_directory: "./chroma_db"
  
# Paths configuration
paths:
  papers_dir: "./papers"
  output_dir: "./output"
  log_dir: "./log"
  metadata_dir: "./metadata"
  
# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_rotation: true
  max_file_size_mb: 10
  backup_count: 5
